### ISSUE TITLE
Allow saving as pdf

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/capture-website#80] opened 2021-04-03 06:56 UTC
[Related SA question](https://stackoverflow.com/questions/6896592/is-it-possible-to-save-html-page-as-pdf-using-javascript-or-jquery)

**Comment by sindresorhus** [comment] 2021-04-03 09:15
Can you propose what it would look like? Maybe an `outputType` option? Does Puppeteer support PDF? If so, can you link to relevant docs?

**Comment by Richienb** [comment] 2021-04-03 11:33
[`page.pdf`](https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagepdfoptions)

**Comment by hlovdal** [comment] 2023-01-10 21:50
This is a duplicate of #108 (or actually vice versa), so this issue could probably be closed.

**Comment by sindresorhus** [comment] 2023-01-11 05:43
Duplicate of #108

**Closed by sindresorhus** 2023-01-11 05:43 UTC
